site: Atellas23
url: https://atellas23.github.io
title: Atellas23
description: Atellas23
twitter:
  username: atellas23
  card: summary
permalink: pretty
presentation: Welcome to my webpage! My name's Àlex, I'm a Data Science and Mathematics student at CFIS-UPC. Please refer to the several subpages for more information on my work, my projects and myself.

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  files:
    output: true
    permalink: /files/:name
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      
  - scope:
      path: "assets/images"
    values:
      image: true
