site: Atellas23
url: https://atellas23.github.io
title: Atellas23
description: Atellas23
# twitter:
#   username: yourusername
#   card: summary
permalink: pretty
presentation: Welcome to my page! Here I present some of my projects, academic and non-academic. If you want to contact me, you can see how to do that in the About page at the top.

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      
  - scope:
      path: "assets/images"
    values:
      image: true
